// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-anlQJU7ntMoxGzPxiktQWb6-Lh4Ucg',
    appId: '1:1076988885263:web:cffe14837f6dd40654267a',
    messagingSenderId: '1076988885263',
    projectId: 'mymoodie-9126a',
    authDomain: 'mymoodie-9126a.firebaseapp.com',
    storageBucket: 'mymoodie-9126a.firebasestorage.app',
    measurementId: 'G-BW9FBRHW5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlNGdo7h7PWeol_84j1hi-O1LfQc0Gug',
    appId: '1:1076988885263:android:7348a96c625351fc54267a',
    messagingSenderId: '1076988885263',
    projectId: 'mymoodie-9126a',
    storageBucket: 'mymoodie-9126a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05rcnuRmW7oIVJ0X_Gaiv3-g38J45LBE',
    appId: '1:1076988885263:ios:fae92691a0e799c854267a',
    messagingSenderId: '1076988885263',
    projectId: 'mymoodie-9126a',
    storageBucket: 'mymoodie-9126a.firebasestorage.app',
    iosBundleId: 'com.example.mymoodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05rcnuRmW7oIVJ0X_Gaiv3-g38J45LBE',
    appId: '1:1076988885263:ios:fae92691a0e799c854267a',
    messagingSenderId: '1076988885263',
    projectId: 'mymoodie-9126a',
    storageBucket: 'mymoodie-9126a.firebasestorage.app',
    iosBundleId: 'com.example.mymoodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv-anlQJU7ntMoxGzPxiktQWb6-Lh4Ucg',
    appId: '1:1076988885263:web:b3511577ce19e29454267a',
    messagingSenderId: '1076988885263',
    projectId: 'mymoodie-9126a',
    authDomain: 'mymoodie-9126a.firebaseapp.com',
    storageBucket: 'mymoodie-9126a.firebasestorage.app',
    measurementId: 'G-PMMGNH2LTG',
  );
}
